### ISSUE TITLE
URL routing not working; getting 404 Not Found.

### ISSUE THREAD

**Issue by markser** [codeu-spring-2019-team-9/codeu-spring-2019-team-9#7]
appengine-maven-plugin: **2.0.0-rc5**, would not be able to access the servlets at all. Had 404 error

after changing the version to **1.9.56,** had no errors and servlets worked as intended.

**Comment by michaelsafyan** [comment]
Instead of using the `@WebServlet` annotation to do URL routing, can you use the 'web.xml' file to configure routing? To my understanding, the 'web.xml' approach should work.

Please see:
https://cloud.google.com/appengine/docs/standard/java/config/webxml

**Comment by michaelsafyan** [comment]
Alternatively, these solutions may allow the `@WebServlet` annotation to work:
https://javatutorial.net/servlet-annotation-example

**Comment by michaelsafyan** [comment]
I'll look into getting it to work with `@WebServlet`.

**Comment by michaelsafyan** [comment]
I've just submitted commit `72267b18b75e64b8bd8b03fdf07682241630ea4c`, which fixes URL routing and provides an example of how to do URL routing using the XML-based configuration.

I tried to get the `@WebServlet` annotation to work a number of ways, but ultimately couldn't get it to work without downgrading to the deprecated plugin. Let's just use the XML approach.
